# Usa la imagen base de Node.js
FROM node:16

# Crea un directorio de trabajo
WORKDIR /usr/src/app

# Copia los archivos de definición de paquetes
COPY package*.json ./

# Instala las dependencias de producción y el CLI de NestJS
RUN npm install --production

# Instala las dependencias de desarrollo, incluyendo @nestjs/cli y @types/node
RUN npm install --save-dev @nestjs/cli @types/node

# Copia el resto de la aplicación
COPY . .

# Compila la aplicación
RUN npm run build

# Expone el puerto en el que se ejecutará la aplicación
EXPOSE 3000

# Comando para iniciar la aplicación
CMD ["npm", "run", "start:prod"]
