version: '3.8'  # Actualizado a la versión más reciente

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - MONGODB_URI=mongodb+srv://Scorhenao:Samuelpro.2006@library.boubc.mongodb.net/library-db?retryWrites=true&w=majority&appName=library
    depends_on:
      - mongo
    restart: always  # Reinicia el contenedor si se detiene

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    restart: always  # Reinicia el contenedor si se detiene

volumes:
  mongo-data:
